env:
  ENTERPRISE: '1'
  MINIFY: '1'
  FORCE_COLOR: '3'

steps:
  - command:
      - COVERAGE_INSTRUMENT=true NODE_OPTIONS="--max_old_space_size=4096" dev/ci/yarn-run.sh build-storybook
      - yarn --cwd client/shared run download-puppeteer-browser
      - yarn run cover-storybook
      - yarn nyc report -r json
      - bash <(curl -s https://codecov.io/bash) -c -F typescript -F storybook
    label: ':storybook::codecov: Storybook coverage'
  - command:
      - dev/ci/yarn-build.sh client/web
      - dev/ci/create-client-artifact.sh
    key: lighthouse:prep
    label: ':lighthouse: Lighthouse production build'
    env:
      NODE_ENV: production
      WEBPACK_SERVE_INDEX: 'true'
  - command: dev/ci/yarn-lighthouse.sh homepage /
    depends_on: lighthouse:prep
    label: ':lighthouse: lighthouse:homepage'
    env:
      SOURCEGRAPH_API_URL: https://sourcegraph.com
  - command: dev/ci/yarn-lighthouse.sh search_results /search?q=repo:sourcegraph/sourcegraph+file:package.json
    depends_on: lighthouse:prep
    label: ':lighthouse: lighthouse:search_results'
    env:
      SOURCEGRAPH_API_URL: https://sourcegraph.com
  - command: dev/ci/yarn-lighthouse.sh file_blob /github.com/sourcegraph/sourcegraph/-/blob/package.json
    depends_on: lighthouse:prep
    label: ':lighthouse: lighthouse:file_blob'
    env:
      SOURCEGRAPH_API_URL: https://sourcegraph.com
