name: "Notify users based on issue labels"

on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/issue-label-notification-action@f2d97bbacfaccffab5f4fb09a003f67416c253ef
          with:
             recipients: |
                  team/extensibility=@muratsu
                  team/cloud=@RafLeszczynski
                  team/search-product=@benvenker @lguychard
                  team/search-core=@jjeffwarner
                  [deprecated]team/search=@lguychard @benvenker @jjeffwarner
                  team/code-intelligence=@macraig
                  team/code-insights=@joelkw @felixfbecker @vovakulikov @unclejustin
                  team/distribution=@dan-mckean
                  team/delivery=@dan-mckean @caugustus-sourcegraph @kevinwojo
                  team/security=@dcomas
                  team/dev-experience=@taylorsperry @jhchabran @kstretch9
                  team/repo-management=@jplahn @dan-mckean
                  team/devops=@daxmc99 @bcreager
                  team/cloud-growth=@muratsu @rrhyne
