name: CI
on: [push]

jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # set up correct version of node
      - id: nvmrc
        run: echo ::set-output name=NODE_VERSION::$(cat .nvmrc)
      - uses: actions/setup-node@v2
        with: { node-version: '${{ steps.nvmrc.outputs.NODE_VERSION }}' }

      - run: yarn install && npm install -g @lhci/cli@0.8.x

      - name: Build
        env:
          NODE_ENV: production
          WEBPACK_SERVE_INDEX: true
          SOURCEGRAPH_API_URL: https://sourcegraph.com
        run: yarn workspace @sourcegraph/web run build

      - name: Run
        env:
          NODE_ENV: production
          WEBPACK_SERVE_INDEX: true
          SOURCEGRAPH_API_URL: https://sourcegraph.com
        run: lhci autorun
