name: sg setup check
on: 
  push: 
    paths:
      - 'dev/sg/**'
      - '.github/workflows/sg-testing.yml'
  pull_request:
    paths:
      - 'dev/sg/**'
      - '.github/workflows/sg-testing.yml'

env:
  GOFLAGS: -trimpath
  CGO_ENABLED: '0'

jobs:
  test_macos:
    runs-on: macos-11
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout
        uses: actions/checkout@v2

      - name: install sg
        run: |
          pushd dev/sg 
          go build -ldflags "-X main.BuildCommit=$(git rev-list -1 HEAD .)" .
          ./sg -y install
          . ~/.bashrc
          sg version
          popd

      - name: run setup command
        run: |
          . ~/.bashrc
          sg -y setup

      - name: run setup commands manually
        run: |
          set -x
          # brew install --cask docker
          # brew install git gnu-sed comby pcre sqlite jq
          # # brew install go yarn node # skipping those to avoid clashing with what's already present on the VM
          # brew install postgres redis
          # brew services start postgresql
          # brew services start redis
          # (hash psql && echo "OK") || echo "NOT OK"
          # . ~/.bash_profile 
          # which psql
          # NVM_VERSION="$(curl https://api.github.com/repos/nvm-sh/nvm/releases/latest | jq -r .name)"
          # curl -L https://raw.githubusercontent.com/nvm-sh/nvm/"$NVM_VERSION"/install.sh -o /tmp/install-nvm.sh
          # sh /tmp/install-nvm.sh 
          # export NVM_DIR="$HOME/.nvm"
          # [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          # nvm install
          # # nvm use --delete-prefix # <- this fails, not sure why
          # createdb
          # createuser --superuser sourcegraph
          # psql -c "ALTER USER sourcegraph WITH PASSWORD 'sourcegraph';"
          # createdb --owner=sourcegraph --encoding=UTF8 --template=template0 sourcegraph
          sudo ./dev/add_https_domain_to_hosts.sh
          brew install nss
          ./dev/caddy.sh trust 

      - name: run sg doctor
        run: |
          . ~/.bashrc
          sg doctor


