name: SG Testing
on: 
  push: 
    paths:
      - 'dev/sg/**'
      - '.github/workflows/sg-testing.yml'
  pull_request:
    paths:
      - 'dev/sg/**'
      - '.github/workflows/sg-testing.yml'

env:
  GOFLAGS: -trimpath
  CGO_ENABLED: '0'

jobs:
  test_macos:
    runs-on: macos-11
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install SG
        run: |
          ls -al /usr/local/bin
          cd dev/sg && go build -ldflags "-X main.BuildCommit=$(git rev-list -1 HEAD .)" .
          sudo ./sg -y install
          sg version
